export { default as Hero } from "./Hero";
export { default as BusinessTypes } from "./businessTypes";
export { default as Services } from "./services";
export { default as OurClient } from "./ourClient";
export { default as OurTechStack } from "./our-tech-stack";
export { default as IndustriesCards } from "./cards";
export { default as TriScroll } from "./triScroll";
export { default as RealEstatePartner } from "./realEstatepatner";
export { default as DigitalServices } from "./digitalServices";
