export { default as IndustriesHero } from "./hero";
export { default as OtherSuccessStoriesSlider } from "./OtherSuccessStoriesSlider";
export { default as ChooseQubitars } from "./chooseQubitars";
export { default as BusinessExcellence } from "./businessExcellence";
export { default as OutcomeFocused } from "./outcomeFocused";
export { default as IndustriesAbout } from "./about";
export { default as GrowthBarrier } from "./growthbarrier";
export { default as Solutions } from "./solutions";
export { default as FAQs } from "./FAQs";