import type { Metadata } from "next";
import { DM_Sans, Poppins, Fjalla_One } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/navbar";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const fjallaOne = Fjalla_One({
  variable: "--font-fjalla-one",
  subsets: ["latin"],
  weight: ["400"],
});

const satoshi = localFont({
  src: "./fonts/Satoshi.otf",
  style: "normal",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Qubitars Technology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${poppins.variable} ${satoshi.variable} ${fjallaOne.variable} antialiased`}
      >
        <div className="fixed top-0 z-40 w-full">
          <Header />
        </div>
        <main className="flex-1 pt-[5.8rem] md:pt-[6.1rem]">
          {children}
        </main>
      </body>
    </html>
  );
}
